#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_gradient_ps.h /Vn g_gradient_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_gradient_ps.hlsl
//
//
// Parameters:
//
//   float time;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   time         c0       1
//

// Shader type: pixel 

xps_3_0
defconst time, float, scalar, [1, 1], c0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1

def c252, 0, 0, 0, 0
def c253, 0, 0, 0, 0
def c254, 0, 0, 0, 0
def c255, -3.14159274, 0.5, 0.159154937, 6.28318548


    alloc colors
    exece
    mad r0.z, c0.x, c255.z, c255.y
    frcs r0.z, r0.z
    mad r0.z, r0.z, c255.w, c255.x
    sin r0.z, r0.z
    mad r0.z, r0.z, c255.y, c255.y
    mov oC0.xyz1, r0.xyz

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_gradient_bin[] =
{
    0x102a1100, 0x000000d4, 0x000000a0, 0x00000000, 0x00000024, 0x00000084, 
    0x000000ac, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00010000, 0x00000038, 0x00000000, 0x74696d65, 0x00ababab, 
    0x00000003, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000001, 0x00000000, 
    0x00000000, 0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000040, 0x00000060, 0x10000100, 0x00000008, 0x00000000, 
    0x00001842, 0x00010003, 0x00000001, 0x00003050, 0x0000f1a0, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0xc0490fdb, 
    0x3f000000, 0x3e22f983, 0x40c90fdb, 0x00000000, 0x6001c400, 0x22000000, 
    0xc8040000, 0x006cc6b1, 0x0b00ffff, 0x2c400000, 0x000000c6, 0xe2000000, 
    0xc8040000, 0x00c61b6c, 0x8b00ffff, 0xc0400000, 0x000000c6, 0xe2000000, 
    0xc8040000, 0x00c6b1b1, 0x8b00ffff, 0xc88fc000, 0x00c0c000, 0xe2000000, 
    0x00000000, 0x00000000, 0x00000000
};
