#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_plasma_ps.h /Vn g_plasma_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_plasma_ps.hlsl
//
//
// Parameters:
//
//   float time;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   time         c0       1
//

// Shader type: pixel 

xps_3_0
defconst time, float, scalar, [1, 1], c0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1

def c252, 0, 0, 0, 0
def c253, -3.14159274, 0.125000283, 0.159154937, 0
def c254, 1.29999995, 1.70000005, -5, 6.28318548
def c255, 0.5, 0.832633793, 1.16685915, 10


    alloc colors
    exec
    mul r0.zw, c0.x, c254.xxxy
    mul r1.xy, r0.xy, c255.w
    add r1.zw, r1.xxxy, c254.z
  + adds r0.y, r1.xy
    dp2add r0.x, r1.zw, r1.zw, c253.w
    mul r1.z, r0.y, c255.x
  + sqrt r0.x, r0_abs.x
    add r0.w, -r0.w, r0.x
  + movs r0._, r1.y
    exec
    add r0.xy, r1.xz, c0.x
  + adds_prev r0.z, r0.z
    mad r0, r0.wxyz, c253.z, c255.x
    frc r0, r0.wxyz
    mad r0, r0.yxzw, c254.w, c253.x
    sin r1.y, r0.z
    sin r1.x, r0.y
    exec
    add r1.y, r1.y, r1.x
  + sin r1.x, r0.w
    add r0.y, r1.y, r1.x
  + sin r0.x, r0.x
    add r0.x, r0.y, r0.x
    mad r0.xyz, r0.x, c253.y, c255.xyz
    frc r0.xyz, r0.xyz
    mad r0.xyz, r0.xyz, c254.w, c253.x
    exece
    sin r0.x, r0.x
    sin r0.y, r0.y
    sin r0.z, r0.z
    mad oC0.xyz1, r0.xyz, c255.x, c255.x

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_plasma_bin[] =
{
    0x102a1100, 0x000000d4, 0x00000178, 0x00000000, 0x00000024, 0x00000084, 
    0x000000ac, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00010000, 0x00000038, 0x00000000, 0x74696d65, 0x00ababab, 
    0x00000003, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000001, 0x00000000, 
    0x00000000, 0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000040, 0x00000138, 0x10000100, 0x00000008, 0x00000000, 
    0x00001842, 0x00010003, 0x00000001, 0x00003050, 0x0000f1a0, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0xc0490fdb, 0x3e000013, 0x3e22f983, 
    0x00000000, 0x3fa66666, 0x3fd9999a, 0xc0a00000, 0x40c90fdb, 0x3f000000, 
    0x3f55277d, 0x3f955ba4, 0x41200000, 0x00000000, 0x6003c400, 0x12000000, 
    0x00006009, 0x600f1200, 0x12000000, 0x00004015, 0x00002200, 0x00000000, 
    0xc80c0000, 0x006cac00, 0x2100fe00, 0xc8030001, 0x00b01b00, 0xa100ff00, 
    0x002c0001, 0x00acc661, 0xa001fe01, 0xc8010000, 0x001a1a1b, 0xd10101fd, 
    0xa0140001, 0x00b16c6c, 0xa100ff80, 0x14080000, 0x041b6cb1, 0xe0000001, 
    0x04430000, 0x00c46cc6, 0xa0010000, 0xc80f0000, 0x00ffc66c, 0x8b00fdff, 
    0xc80f0000, 0x00ff0000, 0xe8000000, 0xc80f0000, 0x000d1b6c, 0x8b00fefd, 
    0xc0200100, 0x000000c6, 0xe2000000, 0xc0100100, 0x000000b1, 0xe2000000, 
    0xc0120101, 0x00b16c1b, 0xe0010100, 0xc0120000, 0x00b16c6c, 0xe0010100, 
    0xc8010000, 0x00b16c00, 0xe0000000, 0xc8070000, 0x006cb1c0, 0x8b00fdff, 
    0xc8070000, 0x00c00000, 0xe8000000, 0xc8070000, 0x00c01b6c, 0x8b00fefd, 
    0xc0100000, 0x0000006c, 0xe2000000, 0xc0200000, 0x000000b1, 0xe2000000, 
    0xc0400000, 0x000000c6, 0xe2000000, 0xc88fc000, 0x00c06c6c, 0x8b00ffff, 
    0x00000000, 0x00000000, 0x00000000
};
