#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_rings_ps.h /Vn g_rings_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\fx_rings_ps.hlsl
//
//
// Parameters:
//
//   float time;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   time         c0       1
//

// Shader type: pixel 

xps_3_0
defconst time, float, scalar, [1, 1], c0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1

def c252, 0, 0, 0, 0
def c253, -3.14159274, 6.28318548, 0, 0
def c254, -0.5, 0.159154937, 1, 3
def c255, 0.275000006, 0.5, 42, 0


    alloc colors
    exec
    add r0.xy, r0.xy, c254.x
    dp2add r0.y, r0.xy, r0.xy, c255.w
    mul r0.x, c0.x, c254.w
  + sqrt r0.y, r0_abs.y
    mad r0.x, r0.y, c255.z, -r0.x
    mad r0.x, r0.x, c254.y, c255.y
    frcs r0.x, r0.x
    exece
    mad r0.x, r0.x, c253.y, c253.x
    sin r0.x, r0.x
    mad r0.xy, r0.x, c255.yx, c255.yx
    subsc r0.z, c254.z, r0.x
    mov oC0.xyz1, r0.xyz

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_rings_bin[] =
{
    0x102a1100, 0x000000d4, 0x000000e8, 0x00000000, 0x00000024, 0x00000084, 
    0x000000ac, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00010000, 0x00000038, 0x00000000, 0x74696d65, 0x00ababab, 
    0x00000003, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000001, 0x00000000, 
    0x00000000, 0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000040, 0x000000a8, 0x10000100, 0x00000008, 0x00000000, 
    0x00001842, 0x00010003, 0x00000001, 0x00003050, 0x0000f1a0, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0xc0490fdb, 0x40c90fdb, 0x00000000, 
    0x00000000, 0xbf000000, 0x3e22f983, 0x3f800000, 0x40400000, 0x3e8ccccd, 
    0x3f000000, 0x42280000, 0x00000000, 0x00000000, 0x6002c400, 0x12000000, 
    0x00005008, 0x00002200, 0x00000000, 0xc8030000, 0x00b06c00, 0xa000fe00, 
    0xc8020000, 0x00b0b01b, 0xd10000ff, 0xa0210000, 0x006c1bb1, 0x2100fe80, 
    0xc8010000, 0x01b1c66c, 0xab00ff00, 0xc8010000, 0x006cb1b1, 0x8b00feff, 
    0x2c100000, 0x0000006c, 0xe2000000, 0xc8010000, 0x006cb16c, 0x8b00fdfd, 
    0xc0100000, 0x0000006c, 0xe2000000, 0xc8030000, 0x006c6d6d, 0x8b00ffff, 
    0xb8400000, 0x000000c0, 0xc20000fe, 0xc88fc000, 0x00c0c000, 0xe2000000, 
    0x00000000, 0x00000000, 0x00000000
};
