#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\text_ps.h /Vn g_text_ps_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\text_ps.hlsl
//
//
// Parameters:
//
//   sampler2D fontTex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   fontTex      s0       1
//

// Shader type: pixel 

xps_3_0
defconst fontTex, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1


    exec
    tfetch2D r0.1w__, r0.xy, tf0
    alloc colors
    exece
    mul oC0, r0.xxxy, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_text_ps_bin[] =
{
    0x102a1100, 0x000000ac, 0x0000003c, 0x00000000, 0x00000024, 0x00000000, 
    0x00000084, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00030000, 0x00010000, 0x00000038, 0x00000000, 0x666f6e74, 0x54657800, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x0000003c, 0x10000100, 
    0x00000008, 0x00000000, 0x00001842, 0x00010003, 0x00000001, 0x00003050, 
    0x0000f1a0, 0x00011002, 0x00001200, 0xc4000000, 0x00001003, 0x00002200, 
    0x00000000, 0x10080001, 0x1f1fffdd, 0x00004000, 0xc80f8000, 0x00ac0000, 
    0xe1000100, 0x00000000, 0x00000000, 0x00000000
};
