#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\tri_ps.h /Vn g_ps_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\tri_ps.hlsl
//
// Shader type: pixel 

xps_3_0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1

dcl_color_centroid r0


    alloc colors
    exece
    mov oC0, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_ps_bin[] =
{
    0x102a1100, 0x0000007c, 0x00000024, 0x00000000, 0x00000024, 0x00000000, 
    0x00000058, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xffff0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x70735f33, 
    0x5f300032, 0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000024, 
    0x10000000, 0x00000000, 0x00000000, 0x00001021, 0x00000001, 0x00000001, 
    0x0000f0a0, 0x00000000, 0x1001c400, 0x22000000, 0xc80f8000, 0x00000000, 
    0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
