#!/usr/bin/env python3
# 2026 - Team Resurgent
# SPDX-License-Identifier: GPL-3.0-or-later
# Part of RXDK - see LICENSE.md for the full GNU GPL v3.
"""Build the RXDK-360 component dashboard (tests/gfx/dash.cpp) end to end.

Same recipe as build_tri.py, with the extra text-overlay shaders. The font
atlas (font_atlas.h) is regenerated by gen_font.ps1 (Windows/GDI) and checked
in; this script does not rebuild it.

  1. fxc.exe -> GPU microcode for the triangle (tri_{vs,ps}) and the text
     overlay (text_{vs,ps}) shaders,
  2. our clang compiles dash.cpp against the stock XDK D3D9 headers,
  3. mktitle.py links + packs the XEX.

    xenia_canary.exe build/dash/dash.xex --headless=true
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
DEFAULT_XDK = r"C:\Program Files (x86)\Microsoft Xbox 360 SDK"
TRIPLE = "powerpc-unknown-xbox360"

CFLAGS = [
    "-std=c++11", "-O2", "-fms-extensions", "-fms-compatibility", "-fdeclspec",
    "-fno-exceptions", "-fno-rtti",
    # Xbox 360 WCHAR is 16-bit UTF-16 (MSVC default); our clang would otherwise
    # emit 32-bit wide-char literals, so any L"..." handed to a Unicode API (XMP
    # song paths, XUI typeface locators, ...) reads back empty/garbled on the BE
    # console. Match the platform ABI.
    "-fshort-wchar",
    "-D_WIN32=1", "-D_M_PPCBE=1", "-D_M_PPC=1", "-D_XBOX=1", "-D_XBOX_VER=200",
    "-D__export=", "-D_SIZE_T_DEFINED", "-D_XM_NO_INTRINSICS_", "-Wno-pragma-pack",
    # xaudio2.h builds its GUIDs with the MSVC non-standard `##-##` token paste
    # (comdecl.h); clang's MS-compat concatenates the spellings once this is not
    # an error. Belongs in the clean generated header layer eventually.
    "-Wno-invalid-token-paste",
]

SHADERS = [
    ("tri_vs.hlsl",  "tri_vs.h",  "vs_3_0", "g_vs_bin"),
    ("tri_ps.hlsl",  "tri_ps.h",  "ps_3_0", "g_ps_bin"),
    ("text_vs.hlsl", "text_vs.h", "vs_3_0", "g_text_vs_bin"),
    ("text_ps.hlsl", "text_ps.h", "ps_3_0", "g_text_ps_bin"),
    ("fx_gradient_ps.hlsl", "fx_gradient_ps.h", "ps_3_0", "g_gradient_bin"),
    ("fx_plasma_ps.hlsl",   "fx_plasma_ps.h",   "ps_3_0", "g_plasma_bin"),
    ("fx_rings_ps.hlsl",    "fx_rings_ps.h",    "ps_3_0", "g_rings_bin"),
]


def run(cmd, cwd=None):
    print("+", " ".join(cmd))
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    if r.returncode != 0:
        sys.stdout.write(r.stdout); sys.stderr.write(r.stderr)
        sys.exit(f"command failed ({r.returncode})")
    return r


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--xdk", default=DEFAULT_XDK)
    ap.add_argument("--clang", default=os.path.join(ROOT, "build", "llvm", "bin", "clang++.exe"))
    ap.add_argument("--fxc", help="fxc.exe (default: <xdk>/bin/win32/fxc.exe)")
    ap.add_argument("--outdir", default=os.path.join(ROOT, "build", "dash"))
    ap.add_argument("--spin", action="store_true",
                    help="windowed 'spin forever' variant for screenshots")
    args = ap.parse_args()

    fxc = args.fxc or os.path.join(args.xdk, "bin", "win32", "fxc.exe")
    xdk_inc = os.path.join(args.xdk, "include", "xbox")
    shdir = os.path.join(HERE, "shaders")
    os.makedirs(args.outdir, exist_ok=True)

    # Stage the media assets next to the xex so a loose xenia run resolves them
    # via game:\ (xenia symlinks game:\ to the xex's folder). The same layout is
    # what goes into the XDVDFS ISO for hardware. Assets come from the user's
    # own XDK sample media -- nothing proprietary is committed to the repo.
    import shutil
    media = os.path.join(args.xdk, "Source", "Samples", "Media")
    ASSETS = [("Video", "Sample.wmv"), ("Sounds", "Electro_1.wav"),
              ("Sounds", "music1.wma"),  # XMP title-playlist track
              ("Xui", "xarialuni.ttf")]  # XUI typeface
    for sub, name in ASSETS:
        srcf = os.path.join(media, sub, name)
        dstd = os.path.join(args.outdir, "Media", sub)
        os.makedirs(dstd, exist_ok=True)
        if os.path.exists(srcf):
            shutil.copyfile(srcf, os.path.join(dstd, name))
            print("staged", os.path.join("Media", sub, name))
        else:
            print("WARNING: asset not found:", srcf)

    # Build the XACT audio banks (.xsb sound bank + .xwb XMA wave bank) from the
    # XDK's XactBasicSound project with xactbld3, then stage them next to the xex.
    # xactbld3 resolves the .xap's relative paths against the CWD and appends the
    # project's ..\..\media\sounds\ output subpath to any given output dir, so we
    # copy the project + its source WAV into a flat temp dir with the paths
    # flattened and build there -- no XDK writes, no admin.
    xactbld = os.path.join(args.xdk, "bin", "win32", "xactbld3.exe")
    xap = os.path.join(args.xdk, "Source", "Samples", "Audio", "XactBasicSound", "XactSounds.xap")
    wav = os.path.join(media, "Sounds", "MusicMono.wav")
    if os.path.exists(xactbld) and os.path.exists(xap) and os.path.exists(wav):
        xdir = os.path.join(args.outdir, "xactbuild")
        os.makedirs(xdir, exist_ok=True)
        shutil.copyfile(wav, os.path.join(xdir, "MusicMono.wav"))
        with open(xap, "r") as f:
            proj = f.read().replace("..\\..\\media\\sounds\\", "")
        with open(os.path.join(xdir, "XactSounds.xap"), "w") as f:
            f.write(proj)
        run([xactbld, "/F", "/XBOX360", "/X:HEADER", "/X:REPORT", "/X:CUELIST",
             "XactSounds.xap"], cwd=xdir)
        snd = os.path.join(args.outdir, "Media", "Sounds")
        os.makedirs(snd, exist_ok=True)
        for b in ("XactSounds.xsb", "XactSounds.xwb"):
            shutil.copyfile(os.path.join(xdir, b), os.path.join(snd, b))
            print("staged", os.path.join("Media", "Sounds", b))
    else:
        print("WARNING: XACT bank sources not found; XACT3 section will be inert")

    for src, hdr, profile, var in SHADERS:
        run([fxc, "/nologo", "/T", profile, "/E", "main",
             "/Fh", os.path.join(shdir, hdr), "/Vn", var, os.path.join(shdir, src)])

    obj = os.path.join(args.outdir, "dash_spin.o" if args.spin else "dash.o")
    cflags = list(CFLAGS) + (["-DDASH_SPIN_FOREVER"] if args.spin else [])
    run([args.clang, "--target=" + TRIPLE] + cflags +
        ["-I", xdk_inc, "-I", HERE, "-c", os.path.join(HERE, "dash.cpp"), "-o", obj])

    xex = os.path.join(args.outdir, "dash_spin.xex" if args.spin else "dash.xex")
    run([sys.executable, os.path.join(ROOT, "tools", "mktitle.py"), obj,
         "--lib", "d3d9,d3dx9,xgraphics,xaudio2,xmcore,xnet,xmedia2,x3daudio,xmp,"
                  "xact3,tracerecording,xsim,xonline,xuirun,xuirender",
         "--coff-dir", os.path.join(ROOT, "build", "coff"),
         "--xdk", os.path.join(args.xdk, "lib", "xbox"), "-o", xex])
    print("\nbuilt", xex)


if __name__ == "__main__":
    main()
