# 2026 - Team Resurgent
# SPDX-License-Identifier: GPL-3.0-or-later
# Part of RXDK - see LICENSE.md for the full GNU GPL v3.
#
# Regenerate tests/gfx/font_atlas.h: an A8 bitmap-font atlas for the component
# dashboard (dash.cpp). ASCII 32..127, a 16x6 grid of 16x16 cells rasterised
# from a monospace system font via GDI, stored as an 8-bit alpha texture.
#
#   powershell -File tests/gfx/gen_font.ps1
#
# NOTE: [Math]::Floor for the row -- PowerShell's [int] cast is banker's
# rounding (round-half-to-even), which sends every i%16==8 cell to the wrong
# row and scrambles the glyph grid.

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$cw = 16; $ch = 16; $cols = 16; $rows = 6
$W = $cw * $cols; $H = $ch * $rows

$bmp = New-Object System.Drawing.Bitmap($W, $H, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::FromArgb(0, 0, 0, 0))
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
$font = New-Object System.Drawing.Font("Consolas", 12, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$fmt = [System.Drawing.StringFormat]::GenericTypographic
# Small left/top margin so glyph ink is padded inside its cell -- otherwise the
# half-texel UV inset in the renderer clips the left column of each glyph.
$padX = 2; $padY = 1
for ($i = 0; $i -lt 96; $i++) {
    $c = [char]($i + 32)
    $cx = ($i % $cols) * $cw
    $cy = [Math]::Floor($i / $cols) * $ch
    $g.DrawString([string]$c, $font, [System.Drawing.Brushes]::White, ($cx + $padX), ($cy + $padY), $fmt)
}
$g.Flush()

$rect = New-Object System.Drawing.Rectangle(0, 0, $W, $H)
$data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$bytes = New-Object byte[] ($W * $H * 4)
[System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
$bmp.UnlockBits($data)
$g.Dispose(); $bmp.Dispose()

$out = Join-Path $PSScriptRoot "font_atlas.h"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by gen_font.ps1: ASCII 32..127, 16x6 grid of 16x16 cells, A8. */")
[void]$sb.AppendLine("#define FONT_ATLAS_W $W")
[void]$sb.AppendLine("#define FONT_ATLAS_H $H")
[void]$sb.AppendLine("#define FONT_CELL_W $cw")
[void]$sb.AppendLine("#define FONT_CELL_H $ch")
[void]$sb.AppendLine("#define FONT_COLS $cols")
[void]$sb.AppendLine("static const unsigned char g_font_a8[$($W*$H)] = {")
$line = "  "
for ($p = 0; $p -lt $W * $H; $p++) {
    $line += "$($bytes[$p*4+3]),"
    if ($line.Length -ge 110) { [void]$sb.AppendLine($line); $line = "  " }
}
if ($line.Trim().Length) { [void]$sb.AppendLine($line) }
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($out, $sb.ToString())
Write-Output "wrote $out ($($W*$H) bytes)"
