#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T vs_3_0 /E main /Fh
//    D:\Git\RXDK-360\tests\gfx\shaders\tri_vs.h /Vn g_vs_bin
//    D:\Git\RXDK-360\tests\gfx\shaders\tri_vs.hlsl
//
//
// Parameters:
//
//   float4x4 matWVP;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   matWVP       c0       4
//

// Shader type: vertex 

xvs_3_0
defconst matWVP, float, matrix_columns, [4, 4], c0-3
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1

dcl_index r0.x
dcl_color o0


    exec
    vfetch r2, r0.x, position
    vfetch r0, r0.x, color
    alloc position
    exec
    mul r1, r2.w, c3.xwzy
    mad r1, r2.z, c2.xwzy, r1
    mad r1, r2.y, c1.xzyw, r1.xzwy
    mad oPos, r2.x, c0, r1.xzyw
    alloc interpolators
    exece
    mov o0, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_vs_bin[] =
{
    0x102a1101, 0x000000bc, 0x00000084, 0x00000000, 0x00000024, 0x00000000, 
    0x00000084, 0x00000000, 0x00000000, 0x0000005c, 0x0000001c, 0x0000004f, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000048, 0x00000030, 
    0x00020000, 0x00040000, 0x00000038, 0x00000000, 0x6d617457, 0x565000ab, 
    0x00030003, 0x00040004, 0x00010000, 0x00000000, 0x76735f33, 0x5f300032, 
    0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000084, 0x00010002, 
    0x00000000, 0x00000000, 0x00001021, 0x00000001, 0x00000002, 0x00000001, 
    0x00000290, 0x00100003, 0x0030a004, 0x0000f0a0, 0x00001009, 0x30052003, 
    0x00001200, 0xc2000000, 0x00004005, 0x00001200, 0xc4000000, 0x00001009, 
    0x00002200, 0x00000000, 0x05f82000, 0x00000688, 0x00000000, 0x05f80000, 
    0x00000688, 0x00000000, 0xc80f0001, 0x001b8800, 0xa1020300, 0xc80f0001, 
    0x00c68800, 0xab020201, 0xc80f0001, 0x00b13494, 0xab020101, 0xc80f803e, 
    0x006c0034, 0xab020001, 0xc80f8000, 0x00000000, 0xe2000000, 0x00000000, 
    0x00000000, 0x00000000
};
